class KenyanCounties {
  List<String> counties = [
    'Nairobi',
    'Mombasa',
    'Kisumu',
    'Nakuru',
    'Eldoret',
    'Kisii',
    'Kakamega',
    'Nyeri',
    'Meru',
    'Embu',
    'Tharaka Nithi',
    'Machakos',
    'Kitui',
    'Makueni',
    'Narok',
    'Bungoma',
    'Siaya',
    'Homa Bay',
    'Migori',
    'Nyamira',
    'Vihiga',
    'Turkana',
    'West Pokot',
    'Samburu',
    'Kwale',
    'Kilifi',
    'Tana River',
    'Lamu',
    'Taita Taveta',
    'Garissa',
    'Wajir',
    'Mandera',
    'Marsabit',
    'Isiolo',
    'Nyandarua',
    'Kirinyaga',
    'Murang\'a',
    'Kiambu',
    'Trans Nzoia',
    'Uasin Gishu',
    'Elgeyo Marakwet',
    'Nandi',
    'Laikipia',
    'Baringo',
    'Kajiado',
    'Kericho',
    'Bomet',
    'Busia',
  ];
}
