name: livestock_repository
description: Dart package which manages the Livestock data.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^5.1.2 
  cloud_firestore: ^5.1.0 
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  uuid: ^4.4.2

  user_repository:
    path: ../user_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true